// SHOULD THROW OUT OF BOUNDS EXCEPTION
main() : int {
    a:int[1][2][3]
    a[0][0][0] = 5
    return a[-1][0][0]
}
